package MA_MSG_Suite_OB;


import okhttp3.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.IOException;
import java.util.Random;

import org.apache.poi.util.Units;
import org.apache.poi.xwpf.usermodel.Document;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;
import org.openqa.selenium.*;
import org.openqa.selenium.support.ui.*;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import io.github.bonigarcia.wdm.WebDriverManager;
import okhttp3.*;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.openqa.selenium.*;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.io.FileInputStream;
import java.io.IOException;
import java.time.Duration;
import java.util.*;

import okhttp3.*;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.openqa.selenium.*;


import java.io.*;
import java.time.Duration;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;

import static MA_MSG_Suite_OB.Main4a5a_OrderScreenshot.document;


public class Main7_MakePickCart {

//    public static String filePath = "C:\\Users\\2210420\\IdeaProjects\\msg-runner\\OOdata.xlsx";
//    public static String testcase = "TST_001"; // You can pass this dynamically
//    public static String env ="DEV";


    public static WebDriver driver;
    public static String cartId;//Load
    public static String locationP = "PT2L100";
    public static int time = 60;

    //NEED TO TAKE CARE OF SHEETNAME
//    public static void main(String[] args) throws IOException, InterruptedException {
//
//
//        Map<String, List<String>> taskGroupToTaskIds = getTaskGroupsForTestcase(filePath, "Tasks", testcase);
//        WebDriverManager.chromedriver().setup();
//        ChromeOptions options = new ChromeOptions();
//        options.addArguments("--start-maximized");
//
//        driver = new ChromeDriver(options);
//        driver.manage().window().maximize();
//        Main1_URL_Login1 login1 = new Main1_URL_Login1(driver, env);
//        login1.execute();
//        System.out.println("login done:");
//        SearchMenuWM("WM Mobile","WMMobile");
//
//        for (Map.Entry<String, List<String>> entry : taskGroupToTaskIds.entrySet()) {
//            String taskGroupId = entry.getKey();
//            List<String> taskIds = entry.getValue();
//            System.out.println("Processing Task Group: " + taskGroupId);
//            SettingtheTaskGroupfromExcel(taskGroupId);
//            int index = 0;
//            while (index < taskIds.size()) {
//                System.out.println("TaskId Size"+taskIds.size());
//                SearchInWmMobile("JD Make Pick Cart", "jdmakepickcart");
//                int count = 1;
//                cartId = WMEnterDynamicCartID();
//
//                if (Nomoretasksdailogbox()) {
//                    System.out.println("Task is in Held Status OR No more tasks dialog detected after MakePickCartandpick.");
//                    backWMMobie();
//                    break;
//                }
//
//                for (int i = 0; i < 6 && index < taskIds.size(); i++) {
//
//                     enterAutoGeneratedTote();
//
//                    clickTapToConfirmButton();
//                    SlotinputButton(String.format("%02d", count));
//                    count++;
//                    System.out.println("print count"+count);
//                    index++;
//                    System.out.println("print index"+index);
//
//                    if (Nomoretasksdailogbox()) {
//                        System.out.println("No more tasks dialog detected. Moving to next task group...");
//                        // ClickEndcart();
//                        Thread.sleep(5000);
//                        clickTapToConfirmButton2();
//                        Thread.sleep(5000);
//                        clickTapToConfirmButton2();
//                        Thread.sleep(5000);
//                        clickTapToConfirmButton2();
//                        Thread.sleep(8000);
//                        ScanCartID(cartId);
//                        Thread.sleep(3000);
//
//                        while (true) {
//                            boolean foundAny = false;
//
//                            if (isElementPresent("acceptlocation_barcodetextfield_location")) {
//                                SourceLocation();
//                                Thread.sleep(3000);
//                                foundAny = true;
//                            }
//
//                            if (isElementPresent("acceptitem_barcodetextfield_item")) {
//                                ItemBarcode();
//                                Thread.sleep(3000);
//                                foundAny = true;
//                            }
//
//                            if (isElementPresent("acceptquantity_naturalquantityfield_need")) {
//                                EnterUnit();
//                                Thread.sleep(3000);
//                                foundAny = true;
//                            }
//
//                            if (isElementPresent("confirmolpntocompletepick_barcodetextfield_olpn")) {
//                                EnterOlpn();
//                                Thread.sleep(3000);
//                                foundAny = true;
//                            }
//
//                            clickOkAlertButton();
//
//                            if (!foundAny) {
//                                System.out.println("🚪 No target elements found. Exiting loop.");
//                                break;
//                            }
//                        }
//
//
//
//                        Thread.sleep(5000);
//                        System.out.println("start ScanCartID2 ");
//                        ScanCartID2(cartId);
//                        Thread.sleep(3000);
//                        Packlocation();
//                        Thread.sleep(5000);
//                        // Wait until the ion-buttons container is present
//                        WmActionBack();
//                        Thread.sleep(3000);
//                       // WmActionSubmenuBack();
//                        Thread.sleep(3000);
//                       // WmActionSubmenuBack();
//
//
//                       // break;
//                    }
//                    // If dialog was detected, break outer loop too
//                    else if ( count == 7 ) {
//                        System.out.println("2nd wala ");
//                        ClickEndcart();
//                        Thread.sleep(5000);
//                        clickTapToConfirmButton2();
//                        Thread.sleep(5000);
//                        clickTapToConfirmButton2();
//                        Thread.sleep(5000);
//                        clickTapToConfirmButton2();
//                        Thread.sleep(8000);
//                        ScanCartID(cartId);
//                        Thread.sleep(3000);
//
//                        while (true) {
//                            boolean foundAny = false;
//
//                            if (isElementPresent("acceptlocation_barcodetextfield_location")) {
//                                SourceLocation();
//                                Thread.sleep(3000);
//                                foundAny = true;
//                            }
//
//                            if (isElementPresent("acceptitem_barcodetextfield_item")) {
//                                ItemBarcode();
//                                Thread.sleep(3000);
//                                foundAny = true;
//                            }
//
//                            if (isElementPresent("acceptquantity_naturalquantityfield_need")) {
//                                EnterUnit();
//                                Thread.sleep(3000);
//                                foundAny = true;
//                            }
//
//                            if (isElementPresent("confirmolpntocompletepick_barcodetextfield_olpn")) {
//                                EnterOlpn();
//                                Thread.sleep(3000);
//                                foundAny = true;
//                            }
//
//                            clickOkAlertButton();
//
//                            if (!foundAny) {
//                                System.out.println("🚪 No target elements found. Exiting loop.");
//                                break;
//                            }
//                        }
//
//
//                        Thread.sleep(5000);
//                        System.out.println("start ScanCartID2 ");
//                        ScanCartID2(cartId);
//                        Thread.sleep(3000);
//                        Packlocation();
//                        Thread.sleep(5000);
//                        // Wait until the ion-buttons container is present
//                        WmActionBack();
//                        Thread.sleep(3000);
//                        // WmActionSubmenuBack();
//                        Thread.sleep(3000);
//                        // WmActionSubmenuBack();
//
//                        // break;
//                    }
//                }
//
//
//            }
//        }
//    }
//

    public static String docPathLocal ;
    public static void main(String filePath, String testcase, String env, String sheetname) throws Exception {

        System.out.println("Make Pick Cart Started for"+ testcase);
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--start-maximized");

        driver = new ChromeDriver(options);
        driver.manage().window().maximize();
        Main1_URL_Login1 login1 = new Main1_URL_Login1(driver, env);
        login1.execute();
        System.out.println("login done:");
        SearchMenuWM("WM Mobile","WMMobile");

        List<String> taskGroups = getTaskGroupsForTestcase1(filePath, sheetname, testcase);
        docPathLocal = DocPathManager.getOrCreateDocPath(filePath, testcase);
        for (String taskGroupId : taskGroups) {
            SettingtheTaskGroupfromExcel(taskGroupId);
            SearchInWmMobile("JD Make Pick Cart", "jdmakepickcart");

            boolean noMoreTasksAfterCart = false;
            do {
                String cartId = WMEnterDynamicCartID();

                if (Nomoretasksdailogbox()) {
                    backWMMobie();
                    noMoreTasksAfterCart = true;
                    break;
                }

                for (int slot = 1; slot <= 6; slot++) {
                    enterAutoGeneratedTote();
                    //clickTapToConfirmButton();


                    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
                    WebElement slotInput = wait.until(ExpectedConditions.elementToBeClickable(
                            By.cssSelector("input[data-component-id='acceptslot_barcodetextfield_slot']")
                    ));
                    Thread.sleep(1000);
                    slotInput.sendKeys(String.format("%02d", slot));
                    Thread.sleep(3000);
                    captureScreenshot("Slot");
                    DocPathManager.saveSharedDocument();
                    System.out.println("Slot screenshot done");
                    Thread.sleep(3000);
                    slotInput.sendKeys(Keys.ENTER);
                    // Thread.sleep(3000);

                    if (Nomoretasksdailogbox()) {
                        endcart();
                        clickTapToConfirmButton2();
                        Thread.sleep(3000);
                        clickTapToConfirmButton2();
                        Thread.sleep(1000);
                        ScanCartID(cartId);
                        Thread.sleep(1000);

                        while (true) {
                            boolean foundAny = false;

                            if (isElementPresent("acceptlocation_barcodetextfield_location")) {
                                SourceLocation();
                                Thread.sleep(1000);
                                foundAny = true;
                            }

                            if (isElementPresent("acceptitem_barcodetextfield_item")) {
                                ItemBarcode();
                                Thread.sleep(1000);
                                foundAny = true;
                            }

                            if (isElementPresent("acceptquantity_naturalquantityfield_need")) {
                                EnterUnit();
                                Thread.sleep(1000);
                                foundAny = true;
                            }

                            if (isElementPresent("confirmolpntocompletepick_barcodetextfield_olpn")) {
                                EnterOlpn();
                                Thread.sleep(1000);
                                foundAny = true;
                            }

                            clickOkAlertButton();

                            if (!foundAny) {
                                System.out.println("🚪 No target elements found. Exiting loop.");
                                break;
                            }
                        }


                        Thread.sleep(3000);
                        System.out.println("start ScanCartID2 ");
                        ScanCartID2(cartId);
                        Thread.sleep(3000);
                        Packlocation();
                        Thread.sleep(3000);
                        // Wait until the ion-buttons container is present
                        //  WmActionBack();
                        // Thread.sleep(3000);
                        // WmActionSubmenuBack();
                        // Thread.sleep(3000);
                        // WmActionSubmenuBack();

                        noMoreTasksAfterCart = true;
                        break;
                    }
                }

                if (!noMoreTasksAfterCart) {
                    endcart();
                    clickTapToConfirmButton2();
                    Thread.sleep(3000);
                    clickTapToConfirmButton2();
                    Thread.sleep(1000);
                    ScanCartID(cartId);
                    Thread.sleep(1000);

                    while (true) {
                        boolean foundAny = false;

                        if (isElementPresent("acceptlocation_barcodetextfield_location")) {
                            SourceLocation();
                            Thread.sleep(1000);
                            foundAny = true;
                        }

                        if (isElementPresent("acceptitem_barcodetextfield_item")) {
                            ItemBarcode();
                            Thread.sleep(1000);
                            foundAny = true;
                        }

                        if (isElementPresent("acceptquantity_naturalquantityfield_need")) {
                            EnterUnit();
                            Thread.sleep(1000);
                            foundAny = true;
                        }

                        if (isElementPresent("confirmolpntocompletepick_barcodetextfield_olpn")) {
                            EnterOlpn();
                            Thread.sleep(1000);
                            foundAny = true;
                        }

                        clickOkAlertButton();

                        if (!foundAny) {
                            System.out.println("🚪 No target elements found. Exiting loop.");
                            break;
                        }
                    }


                    Thread.sleep(3000);
                    System.out.println("start ScanCartID2 ");
                    ScanCartID2(cartId);
                    Thread.sleep(3000);
                    Packlocation();
                    Thread.sleep(3000);
                    // Wait until the ion-buttons container is present
                    // WmActionBack();
                    //Thread.sleep(3000);
                    // WmActionSubmenuBack();
                    // Thread.sleep(3000);
                    // WmActionSubmenuBack();

                }

            } while (!noMoreTasksAfterCart);




        }
        if (driver != null) {
            driver.quit();
        }
        System.out.println(" Make pick Cart Done for Testcase"+testcase);

    }




    // Stub methods for Selenium actions
    public static void SettingtheTaskGroupfromExcel(String taskGroupId) throws InterruptedException {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
        JavascriptExecutor js = (JavascriptExecutor) driver;
        System.out.println("Setting task group: " + taskGroupId);
        // Settings Button
        Thread.sleep(3000);
        // Wait until inner button inside shadow root exists
        new WebDriverWait(driver, Duration.ofSeconds(time)).until(d ->
                Boolean.TRUE.equals(((JavascriptExecutor) d).executeScript(
                        "const host = document.querySelector('ion-button[data-component-id=\"action_settings_button\"]');" +
                                "return host && host.shadowRoot && host.shadowRoot.querySelector('button.button-native') !== null;"
                ))
        );

        // Get the inner button
        WebElement innerButton = (WebElement) js.executeScript(
                "const host = document.querySelector('ion-button[data-component-id=\"action_settings_button\"]');" +
                        "return host.shadowRoot.querySelector('button.button-native');"
        );

        if (innerButton != null) {
            js.executeScript("arguments[0].scrollIntoView(true);", innerButton);
            js.executeScript("arguments[0].click();", innerButton);
            System.out.println("✅ Settings button clicked successfully!");
        } else {
            System.out.println("❌ Inner button still not found.");
        }


        Thread.sleep(3000);
        // Task Group Button
        new WebDriverWait(driver, Duration.ofSeconds(time)).until(d ->
                ((JavascriptExecutor) d).executeScript(
                        "return document.querySelector('ion-col[data-component-id=\"taskgroup\"]') !== null"
                ).equals(true)
        );

        WebElement taskGroup = (WebElement) js.executeScript(
                "return document.querySelector('ion-col[data-component-id=\"taskgroup\"]');"
        );

        if (taskGroup != null) {
            js.executeScript("arguments[0].scrollIntoView(true);", taskGroup);
            js.executeScript("arguments[0].click();", taskGroup);
            System.out.println("✅ Task Group clicked successfully!");
        } else {
            System.out.println("❌ Task Group element not found.");
        }


        Thread.sleep(3000);
        // Task Group Value

        wait = new WebDriverWait(driver, Duration.ofSeconds(time));

        // Wait for input field
        WebElement inputField = wait.until(d ->
                d.findElement(By.cssSelector("input[data-component-id='taskgroup_lookupurl']"))
        );

        // Enter value
        inputField.sendKeys(taskGroupId);


        Thread.sleep(3000);

        captureScreenshot("Task group");
        DocPathManager.saveSharedDocument();
        System.out.println("🔁Task group screenshot done");
        Thread.sleep(3000);

        // Option 1: Press Enter
        inputField.sendKeys(Keys.ENTER);

        WMSettingsclickDoneButton();

    }
    public static void WMSettingsclickDoneButton() {

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
        JavascriptExecutor js = (JavascriptExecutor) driver;
        System.out.println("WMSettingsclickDoneButton");
        try {
            // Step 1: Locate the ion-button with data-component-id
            WebElement shadowHost = wait.until(ExpectedConditions.presenceOfElementLocated(
                    By.cssSelector("ion-button[data-component-id='action_done_button']")
            ));

            // Step 2: Access shadow root
            WebElement innerButton = (WebElement) js.executeScript(
                    "return arguments[0].shadowRoot.querySelector('button.button-native');", shadowHost
            );

            // Step 3: Click the inner button
            if (innerButton != null) {
                js.executeScript("arguments[0].scrollIntoView(true);", innerButton);
                js.executeScript("arguments[0].click();", innerButton);
                System.out.println("✅ 'Done' button clicked successfully!");
            } else {
                System.out.println("❌ Inner button not found inside shadow DOM.");
            }
        } catch (Exception e) {
            System.err.println("❌ Error clicking 'Done' button: " + e.getMessage());
            e.printStackTrace();
        }
    }
    public static void SearchMenuWM(String Keyword, String id)  {
        WebDriverWait wait1 = new WebDriverWait(driver, Duration.ofSeconds(time));
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
        JavascriptExecutor js = (JavascriptExecutor) driver;




        int maxRetries = 6; // Try up to 2 times (1 initial + 1 retry)
        for (int attempt = 1; attempt <= maxRetries; attempt++) {
            System.out.println("⏳ Waiting 10 seconds before refreshing...");

            try {
                Thread.sleep(10000); // Wait 1 minute
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }

//                // 🔄 Click the refresh button inside shadow DOM
//                WebElement refreshHost = driver.findElement(By.cssSelector("ion-button.refresh-button"));
//                js = (JavascriptExecutor) driver;
//                WebElement refreshButton = (WebElement) js.executeScript(
//                        "return arguments[0].shadowRoot.querySelector('button.button-native')", refreshHost);
//                refreshButton.click();
//                System.out.println("🔄 Refresh button clicked.");

            // Locate using data-component-id
            WebElement refreshBtn = wait.until(
                    ExpectedConditions.elementToBeClickable(
                            By.cssSelector("ion-button[data-component-id='refresh']")
                    )
            );

            // Click the button
            refreshBtn.click();

            // Optional: verify action or add logging
            System.out.println("Refresh button clicked successfully!");

            // Optional: wait for UI to settle
            try {
                Thread.sleep(3000);
            } catch (InterruptedException e) {
                throw new RuntimeException(e);
            }

            try {
                WebElement shadowHost = wait1.until(ExpectedConditions.presenceOfElementLocated(
                        By.cssSelector("ion-button[data-component-id='menu-toggle-button']")
                ));
                SearchContext shadowRoot = (SearchContext) js.executeScript("return arguments[0].shadowRoot", shadowHost);
                WebElement nativeButton = shadowRoot.findElement(By.cssSelector("button.button-native"));

// wait for overlay to disappear
                wait1.until(ExpectedConditions.invisibilityOfElementLocated(By.cssSelector("manh-overlay-container")));

// click via JS to avoid interception
                js.executeScript("arguments[0].click();", nativeButton);

                System.out.println("Menu toggle button clicked.");




                break;
            }catch (Exception e) {
                System.err.println("Error: " + e.getMessage());
                e.printStackTrace(System.err);


            }


        }




        try {
            // Locate the inner input directly under ion-input
            WebElement innerInput = wait.until(ExpectedConditions.presenceOfElementLocated(
                    By.cssSelector("ion-input[data-component-id='search-input'] input.native-input")
            ));

            wait.until(ExpectedConditions.elementToBeClickable(innerInput));

            innerInput.clear();
            innerInput.sendKeys(Keyword);
            System.out.println("✅ Search Done: " + Keyword);

        } catch (Exception e) {
            System.err.println("❌ Error interacting with search input: " + e.getMessage());
            e.printStackTrace();
        }
        try {


            // Wait for the button to be present and visible
            WebElement element = wait.until(ExpectedConditions.presenceOfElementLocated(
                    By.cssSelector("button#wmMobile[data-component-id=" + id + "]")
            ));


            ((JavascriptExecutor) driver).executeScript(
                    "arguments[0].scrollIntoView({block: 'center'});", element
            );

            ((JavascriptExecutor) driver).executeScript(
                    "arguments[0].click();", element
            );

            System.out.println("Clicked element with id: " + id);
            ArrayList<String> tabs = new ArrayList<>(driver.getWindowHandles());
            driver.switchTo().window(tabs.get(1));

        } catch (Exception e) {

            System.err.println("Failed to click element with id: " + id);
            e.printStackTrace();

        }


    }
    static void backWMMobie() throws InterruptedException {
        // Wait until the ion-buttons container is present
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
        JavascriptExecutor js = (JavascriptExecutor) driver;

        WebElement backButton = wait.until(ExpectedConditions.presenceOfElementLocated(
                By.cssSelector("ion-buttons[data-component-id='action_back_button']")
        ));

// Scroll into view to ensure visibility
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", backButton);

// Click the button twice using JavaScript

        // js.executeScript("arguments[0].click();", backButton);
        Thread.sleep(300); // brief pause between clicks
        js.executeScript("arguments[0].click();", backButton);

        System.out.println("Back button clicked twice successfully.");
    }
    static void SearchInWmMobile(String Transaction, String ComponentId)  {
        JavascriptExecutor js = (JavascriptExecutor) driver;
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));


        try {


            WebElement searchInput = wait.until(ExpectedConditions.elementToBeClickable(
                    By.cssSelector("ion-searchbar[data-component-id='search'] input[type='search']")));

            // Clear any existing text
            searchInput.clear();

            // Type the search text
            searchInput.sendKeys(Transaction);

            // Optionally, press ENTER if the search requires submission
            searchInput.sendKeys(Keys.ENTER);


//            WebElement searchInput1 = wait.until(ExpectedConditions.elementToBeClickable(
//                    By.cssSelector("input.searchbar-input[placeholder='Search']")));
////                    By.xpath("//input[@type='search' and @placeholder='Search']")));
//            searchInput1.click();
//            searchInput1.clear();
//            Thread.sleep(3000);
//            searchInput1.sendKeys(Transaction);
        } catch (Exception e) {
            System.err.println("❌ Error in "+Transaction + e.getMessage());
            e.printStackTrace();
        }
        // Locate the ion-label using its data-component-id

        WebElement labelElement = wait.until(ExpectedConditions.elementToBeClickable(
                By.cssSelector("ion-label[data-component-id='" + ComponentId + "']")
        ));

        // Scroll into view to ensure it's interactable
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", labelElement);

        // Click using JavaScript (in case native click doesn't work)
        ((JavascriptExecutor) driver).executeScript("arguments[0].click();", labelElement);

        System.out.println("Clicked on" +Transaction+" label.");


    }
    static String WMEnterDynamicCartID() throws InterruptedException {
        JavascriptExecutor js = (JavascriptExecutor) driver;

        // Generate dynamic Cart ID: "PC" + 7 random digits
        String cartId = "PC" + String.format("%07d", new Random().nextInt(10000000));
        System.out.println("Generated Cart ID: " + cartId);

        // Wait for the input field to be present
        //Thread.sleep(15000); //
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
        WebElement inputField = wait.until(driver1 -> (WebElement) js.executeScript(
                "return document.querySelector('input[data-component-id=\"acceptpickcart_barcodetextfield_cartid\"]')"
        ));

        if (inputField != null) {
            inputField.clear(); // Optional: clear existing text
            inputField.sendKeys(cartId);
            Thread.sleep(3000);
            captureScreenshot("cartId");
            DocPathManager.saveSharedDocument();
            System.out.println("🔁cartId screenshot done");
            Thread.sleep(3000);

            inputField.sendKeys(Keys.ENTER);
            System.out.println("Entered Cart ID and pressed Enter.");
        } else {
            System.out.println("Input field for Cart ID not found.");
        }
        return cartId;

    }
    public static void clickTapToConfirmButton() {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
        JavascriptExecutor js = (JavascriptExecutor) driver;

        try {
            // Step 1: Locate the shadow host (ion-button)
            WebElement shadowHost = wait.until(ExpectedConditions.presenceOfElementLocated(
                    By.cssSelector("ion-button[data-component-id='taptoverifydirectedcontainer_taptoconfirm_button']")
            ));

            // Step 2: Access the shadow root and find the inner native button
            WebElement innerButton = (WebElement) js.executeScript(
                    "return arguments[0].shadowRoot.querySelector('button.button-native');", shadowHost
            );

            // Step 3: Click the inner button
            if (innerButton != null) {
                js.executeScript("arguments[0].scrollIntoView(true);", innerButton);
                js.executeScript("arguments[0].click();", innerButton);
                System.out.println("✅ Tap to Confirm button clicked.");
            } else {
                System.out.println("❌ Inner button not found inside shadow DOM.");
            }
        } catch (Exception e) {
            System.err.println("❌ Error clicking Tap to Confirm button: " + e.getMessage());
        }
    }
    public static void clickTapToConfirmButton2() throws InterruptedException {

        System.out.println("Execute clickTapToConfirmButton2");
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
        // Wait for the "Tap to Confirm" button to be clickable
        WebElement tapToConfirmButton = wait.until(ExpectedConditions.elementToBeClickable(
                By.cssSelector("button[data-component-id='action_taptoconfirm_button']")));
        Thread.sleep(3000);
        captureScreenshot("Click Confirm");
        DocPathManager.saveSharedDocument();
        System.out.println("Click Confirm screenshot done");
        Thread.sleep(3000);
        // Click the button
        tapToConfirmButton.click();
    }
    public static void SlotinputButton(String countId) {
        System.out.println("Slot input with ID: " + countId);
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
        // Wait for the input field to be clickable
        WebElement slotInput = wait.until(ExpectedConditions.elementToBeClickable(
                By.cssSelector("input[data-component-id='acceptslot_barcodetextfield_slot']")
        ));

        // Click to focus
        slotInput.click();

        // Send slot ID and press Enter
        slotInput.sendKeys(countId);
        slotInput.sendKeys(Keys.ENTER);
    }
    public static boolean Nomoretasksdailogbox() throws InterruptedException {
        try {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));

            // Wait for the alert wrapper to appear
            WebElement alertWrapper = wait.until(ExpectedConditions.presenceOfElementLocated(
                    By.cssSelector("div.alert-wrapper.ion-overlay-wrapper")
            ));

            // Confirm the message text is correct
            WebElement message = alertWrapper.findElement(By.cssSelector("div.alert-message"));
            if (message.getText().contains("No more tasks to assign")) {
                // Find and click the OK button
                WebElement okButton = alertWrapper.findElement(By.xpath(".//button[span[text()='Ok']]"));
                Thread.sleep(3000);
                captureScreenshot("Nomoretasks");
                DocPathManager.saveSharedDocument();
                System.out.println("Nomoretasks screenshot done");
                Thread.sleep(3000);
                okButton.click();
                System.out.println("Dialog detected and OK button clicked.");
                // ClickEndcart();

                return true;
            }
        } catch (TimeoutException e) {
            // Dialog not present or not ready
        }
        return false;
    }
    static void ClickEndcart() throws InterruptedException {

        try {
            WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
            WebElement endCartButton = wait.until(ExpectedConditions.visibilityOfElementLocated(
                    By.cssSelector("button[data-component-id='action_endcart_button']")));


            endCartButton.click();


        } catch (Exception e) {
            System.out.println("Failed EndCart" + e.getMessage());
        }

    }
    public static void ScanCartID(String cartId) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
        try {
            WebElement cartInput = wait.until(ExpectedConditions.visibilityOfElementLocated(
                    By.cssSelector("input[data-component-id='verifypickcart_barcodetextfield_scancart']")));

            cartInput.clear();
            cartInput.sendKeys(cartId);
            Thread.sleep(3000);
            captureScreenshot("ScanCartID");
            DocPathManager.saveSharedDocument();
            System.out.println("ScanCartID1 screenshot done");
            Thread.sleep(3000);
            cartInput.sendKeys(Keys.ENTER);

        } catch (Exception e) {
            System.out.println("❌ Failed to scan Cart ID: " + e.getMessage());
        }


    }
    public static void ScanCartID2(String cartId) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
        try {
            WebElement cartInput = wait.until(ExpectedConditions.visibilityOfElementLocated(
                    By.cssSelector("input[data-component-id='acceptcart_barcodetextfield_cartid']")));

            cartInput.clear();
            cartInput.sendKeys(cartId);
            Thread.sleep(3000);
            captureScreenshot("ScanCartID");
            DocPathManager.saveSharedDocument();
            System.out.println("ScanCartID2 screenshot done");
            Thread.sleep(3000);
            cartInput.sendKeys(Keys.ENTER);
            System.out.println(" Enter Cart ID: ");

        } catch (Exception e) {
            System.out.println("❌ Failed to scan Cart ID: " + e.getMessage());
        }


    }
    public static boolean clickOkAlertButton() {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
        try {
            WebElement okButton = wait.until(ExpectedConditions.elementToBeClickable(
                    By.xpath("//button[.//span[text()='Ok']]")));
            Thread.sleep(3000);
            captureScreenshot("Alert");
            DocPathManager.saveSharedDocument();
            System.out.println("Alert screenshot done");
            Thread.sleep(3000);

            okButton.click();
            System.out.println("✅ Clicked 'Ok' alert button.");
            return true;
        } catch (TimeoutException e) {
            return false; // Alert not found
        } catch (Exception e) {
            System.out.println("❌ Error checking alert: " + e.getMessage());
            return false;
        }
    }
    public static void WmActionBack() {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
        JavascriptExecutor js = (JavascriptExecutor) driver;
        WebElement backButton = wait.until(ExpectedConditions.presenceOfElementLocated(
                By.cssSelector("ion-buttons[data-component-id='action_back_button']")
        ));

// Scroll into view to ensure visibility
        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", backButton);

// Click the button twice using JavaScript

        //  js.executeScript("arguments[0].click();", backButton);
        //// brief pause between clicks
        js.executeScript("arguments[0].click();", backButton);

        System.out.println("Back button clicked twice successfully.");

    }
    public static void WmActionSubmenuBack() {


        // Locate the Back button using its data-component-id
        WebElement backButton = driver.findElement(
                By.cssSelector("ion-button[data-component-id='action_submenu_back_button']")
        );

        // Scroll into view and click using JavaScript
        JavascriptExecutor js = (JavascriptExecutor) driver;
        js.executeScript("arguments[0].scrollIntoView(true);", backButton);
        js.executeScript("arguments[0].click();", backButton);

        System.out.println("✅ Clicked on 'Back' button.");


    }
    public static void Packlocation() {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
        JavascriptExecutor js = (JavascriptExecutor) driver;
        try {


            WebElement cartInput = wait.until(ExpectedConditions.visibilityOfElementLocated(
                    By.cssSelector("input[data-component-id='acceptlocation_barcodetextfield_destinationlocation']")));

            cartInput.clear();
            cartInput.sendKeys(locationP);
            Thread.sleep(3000);
            captureScreenshot("Packing Location");
            DocPathManager.saveSharedDocument();
            System.out.println("Packing Location screenshot done");
            Thread.sleep(3000);

            cartInput.sendKeys(Keys.ENTER);

            System.out.println("✅ Entered location value: " + locationP);


        } catch (Exception e) {
            System.err.println("❌ Error clicking 'Done' button: " + e.getMessage());
            e.printStackTrace();
        }

    }
    public static void SourceLocation() {
        // Locate the ion-col element and extract its text
        try {
            WebElement locationElement = driver.findElement(By.cssSelector("ion-col[data-component-id='acceptlocation_barcodetextfield_location']"));
            String rawLocation = locationElement.getText(); // e.g., "PKT-L1-01-12-20-B"

            // Remove hyphens
            String cleanedLocation = rawLocation.replace("-", ""); // Result: "PKTL1011220B"

            // Locate the input field and enter the cleaned value
            WebElement inputField = driver.findElement(By.cssSelector("input[data-component-id='acceptlocation_barcodetextfield_scanlocation']"));
            // inputField.clear();
            inputField.sendKeys(cleanedLocation);
            Thread.sleep(3000);
            captureScreenshot("Source Location");
            DocPathManager.saveSharedDocument();
            System.out.println("Source Location screenshot done");
            Thread.sleep(3000);
            inputField.sendKeys(Keys.ENTER);
            System.out.println("Add Location Barcode ");
        } catch (Exception e) {
            System.out.println("❌ Failed to Add Location Barcode " + e.getMessage());
        }


    }
    public static void ItemBarcode() throws IOException {
        // Locate the ion-col element and extract its text
        String token = null;
        try {
            token = getAuthTokenFromExcel();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        if (token == null) {
            System.err.println("❌ Failed to retrieve access token.");
            return;
        }




        try {
            WebElement itemElement = driver.findElement(By.cssSelector("ion-col[data-component-id='acceptitem_barcodetextfield_item']"));
            String itemRaw = itemElement.getText(); // e.g., "0007-1-0-64"
            // String itemCleaned = itemRaw.replace("-", ""); // Result: "00071064"




            String itemCleaned = searchItemMaster(itemRaw,token);

            System.out.println(itemCleaned);
            //String itemCleaned = "0000071064"; // Result: "00071064"

            WebElement itemInput = driver.findElement(By.cssSelector("input[data-component-id='acceptitem_barcodetextfield_scanitem']"));
            itemInput.sendKeys(itemCleaned);
            Thread.sleep(3000);
            captureScreenshot("Item ");
            DocPathManager.saveSharedDocument();
            System.out.println("Item screenshot done");
            Thread.sleep(3000);
            itemInput.sendKeys(Keys.ENTER);
            System.out.println("Add ItemBarcode ");
        } catch (Exception e) {
            System.out.println("❌ Failed to Add ItemBarcode " + e.getMessage());
        }


    }

    public static void EnterUnit() {
        // Locate the ion-col element and extract its text
        try {
            // Locate the ion-col element and extract its text
            WebElement quantityElement = driver.findElement(By.cssSelector("ion-col[data-component-id='acceptquantity_naturalquantityfield_need']"));
            String quantityRaw = quantityElement.getText(); // e.g., "6 UNIT"

            // Remove non-digit characters to isolate the number
            String quantityCleaned = quantityRaw.replaceAll("[^0-9]", ""); // Result: "6"

            // Locate the input field and enter the cleaned quantity
            WebElement quantityInput = driver.findElement(By.cssSelector("input[data-component-id='acceptquantity_naturalquantityfield_unit']"));
            quantityInput.sendKeys(quantityCleaned);
            Thread.sleep(3000);
            captureScreenshot("Quantity ");
            DocPathManager.saveSharedDocument();
            System.out.println("Quantity screenshot done");
            Thread.sleep(3000);
            quantityInput.sendKeys(Keys.ENTER);
            System.out.println("Successfully  EnterUnit ");
        } catch (Exception e) {
            System.out.println("❌ Failed to EnterUnit " + e.getMessage());
        }
    }
    public static void EnterOlpn() {
        // Locate the ion-col element and extract its text
        try {
            // Locate the ion-col element and extract its text
            WebElement olpnElement = driver.findElement(By.cssSelector("ion-col[data-component-id='confirmolpntocompletepick_barcodetextfield_olpn']"));
            String olpnValue = olpnElement.getText(); // e.g., "KA701311001708"

            // Input oLPN value
            WebElement olpnInput = driver.findElement(By.cssSelector("input[data-component-id='confirmolpntocompletepick_barcodetextfield_scanolpn']"));
            olpnInput.sendKeys(olpnValue);
            Thread.sleep(3000);
            captureScreenshot("Olpn ");
            DocPathManager.saveSharedDocument();
            System.out.println("Olpn screenshot done");
            Thread.sleep(3000);
            olpnInput.sendKeys(Keys.ENTER);
            System.out.println("Successfully  EnterOlpn ");
        } catch (Exception e) {
            System.out.println("❌ Failed to EnterOlpn " + e.getMessage());
        }
    }
    public static boolean isElementPresent(String dataComponentId) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
        JavascriptExecutor js = (JavascriptExecutor) driver;
        try {
            driver.findElement(By.cssSelector("[data-component-id='" + dataComponentId + "']"));
            return true;
        } catch (NoSuchElementException e) {
            return false;
        }
    }


    public static String getAuthTokenFromExcel() throws IOException {
        ExcelReader reader = new ExcelReader();

// By header name
        String LOGIN_URL = reader.getCellValueByHeader(1, "LOGIN_URL");
        String UIUsername = reader.getCellValueByHeader(1, "username");
        String UIPassword = reader.getCellValueByHeader(1, "password");

        reader.close();


        // Step 2: Call token API
        OkHttpClient client = new OkHttpClient();
        MediaType mediaType = MediaType.parse("application/x-www-form-urlencoded");
        RequestBody body = RequestBody.create(mediaType,
                "grant_type=password&username=" + UIUsername + "&password=" + UIPassword);

        Request request = new Request.Builder()
                .url(LOGIN_URL)
                .method("POST", body)
                .addHeader("Content-Type", "application/x-www-form-urlencoded")
                .addHeader("Authorization", "Basic dWpkc3N0YWdlMTpFYXJ0aC1Nb29uLVN1bjE=")
                .build();

        Response response = client.newCall(request).execute();
        String responseBody = response.body() != null ? response.body().string() : null;
        JsonObject json = JsonParser.parseString(responseBody).getAsJsonObject();

        return json.has("access_token") ? json.get("access_token").getAsString() : null;
    }


    public static String searchItemMaster(String itemId, String token) throws IOException {
        // Read environment headers from your ExcelReader
        ExcelReader reader = new ExcelReader();
        String BASE_URL = reader.getCellValueByHeader(1, "BASE_URL");
        String SelectedOrganization = reader.getCellValueByHeader(1, "SelectedOrganization");
        String SelectedLocation = reader.getCellValueByHeader(1, "SelectedLocation");
        reader.close();

        // Build request body
        String body = "{\"Query\":\"ItemId in ('" + itemId + "')\"}";

        OkHttpClient client = new OkHttpClient();
        MediaType mediaType = MediaType.parse("application/json");
        RequestBody requestBody = RequestBody.create(body, mediaType);

        Request request = new Request.Builder()
                .url(BASE_URL + "/item-master/api/item-master/item/search?size=200")
                .method("POST", requestBody)
                .addHeader("Content-Type", "application/json")
                .addHeader("SelectedOrganization", SelectedOrganization)
                .addHeader("SelectedLocation", SelectedLocation)
                .addHeader("Authorization", "Bearer " + token)
                .build();

        Response response = client.newCall(request).execute();
        String responseBody = response.body() != null ? response.body().string() : null;

        if (responseBody == null || responseBody.isEmpty()) {
            return null;
        }

        // Parse JSON and extract CodeValue
        ObjectMapper mapper = new ObjectMapper();
        JsonNode root = mapper.readTree(responseBody);

        JsonNode dataNode = root.path("data");
        if (dataNode.isArray() && dataNode.size() > 0) {
            JsonNode itemCodeNode = dataNode.get(0).path("ItemCode");
            if (itemCodeNode.isArray() && itemCodeNode.size() > 0) {
                return itemCodeNode.get(0).path("CodeValue").asText();
            }
        }

        return null; // fallback if not found
    }

    public static void switchMode() {
        // Assumes a class-level WebDriver field: private WebDriver driver;
        WebDriverWait wait = new WebDriverWait(driver, java.time.Duration.ofSeconds(time));

        java.util.List<By> locators = java.util.Arrays.asList(
                By.cssSelector("button[data-component-id='action_switchmode_button']"),
                By.xpath("//span[normalize-space()='Switch Mode']/ancestor::button[1]"),
                By.xpath("//button[.//span[normalize-space()='Switch Mode']]"),
                By.xpath("//button[contains(normalize-space(.), 'Switch Mode')]")
        );

        org.openqa.selenium.WebElement target = null;

        // Try up to 3 attempts to account for dynamic DOM updates
        for (int attempt = 0; attempt < 3; attempt++) {
            for (By by : locators) {
                try {
                    target = wait.until(org.openqa.selenium.support.ui.ExpectedConditions.presenceOfElementLocated(by));
                    wait.until(org.openqa.selenium.support.ui.ExpectedConditions.visibilityOf(target));

                    // Scroll into view (helps with overlays/fixed headers)
                    try {
                        ((org.openqa.selenium.JavascriptExecutor) driver)
                                .executeScript("arguments[0].scrollIntoView({block:'center', inline:'center'});", target);
                    } catch (Exception ignored) { }

                    // Ensure clickable (re-resolve if stale)
                    try {
                        wait.until(org.openqa.selenium.support.ui.ExpectedConditions.elementToBeClickable(target));
                    } catch (org.openqa.selenium.StaleElementReferenceException sere) {
                        target = wait.until(org.openqa.selenium.support.ui.ExpectedConditions.elementToBeClickable(by));
                    }

                    // Try standard click, then Actions, then JS fallback
                    try {
                        target.click();
                        return;
                    } catch (org.openqa.selenium.WebDriverException e1) {
                        try {
                            new org.openqa.selenium.interactions.Actions(driver)
                                    .moveToElement(target)
                                    .pause(java.time.Duration.ofMillis(100))
                                    .click()
                                    .perform();
                            return;
                        } catch (Exception e2) {
                            ((org.openqa.selenium.JavascriptExecutor) driver).executeScript("arguments[0].click();", target);
                            return;
                        }
                    }
                } catch (Exception ignored) {
                    // try next locator
                }
            }

            // Small backoff before retrying (helps Angular/Ionic stabilization)
            try { Thread.sleep(500); } catch (InterruptedException ie) { Thread.currentThread().interrupt(); }
        }

        throw new org.openqa.selenium.NoSuchElementException("Failed to click 'Switch Mode' button after multiple attempts.");
    }

    public static void enterOlpnsWithSlots(WebDriver driver, List<String> olpns) {
        // Locators for the two fields
        By containerLocator = By.cssSelector("input[data-component-id='acceptcontainer_barcodetextfield_container']");
        By slotLocator      = By.cssSelector("input[data-component-id='acceptslot_barcodetextfield_slot']");

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));

        int slot = 1; // starts at 01 and goes up to 06, then wraps to 01 again

        for (String olpn : olpns) {
            // 1) Enter OLPN in "Scan Container" and press Enter
            WebElement container = wait.until(ExpectedConditions.elementToBeClickable(containerLocator));
            container.click();

            // Clear safely (CTRL+A + DELETE covers Angular bound inputs)
            container.sendKeys(Keys.chord(Keys.CONTROL, "a"));
            container.sendKeys(Keys.DELETE);

            container.sendKeys(olpn);
            container.sendKeys(Keys.ENTER);

            // 2) Wait for "Scan Slot" field to be visible, enter slot (zero-padded), press Enter
            WebElement slotField = wait.until(ExpectedConditions.visibilityOfElementLocated(slotLocator));
            String slotStr = String.format("%02d", slot);

            slotField.click();
            slotField.sendKeys(Keys.chord(Keys.CONTROL, "a"));
            slotField.sendKeys(Keys.DELETE);
            slotField.sendKeys(slotStr);
            slotField.sendKeys(Keys.ENTER);


            // 3) Wait until the UI returns to the container state for the next OLPN
            //    (either slot disappears or the container becomes clickable again)
            //    Using container readiness as the loop guard for next iteration:
            wait.until(ExpectedConditions.elementToBeClickable(containerLocator));

            // 4) Increment slot and wrap after 06
            slot++;
            if (slot > 6) slot = 1;
        }
    }
    public static List<String> fetchOlpnsByTestcase(String excelPath, String testcaseValue) throws Exception {
        List<String> olpns = new ArrayList<>();
        DataFormatter formatter = new DataFormatter(); // preserves leading zeros

        try (FileInputStream fis = new FileInputStream(excelPath);
             Workbook wb = new XSSFWorkbook(fis)) {

            Sheet sheet = wb.getSheet("tasks");
            if (sheet == null) {
                throw new IllegalArgumentException("Sheet 'tasks' not found in: " + excelPath);
            }

            // Locate header row (assumed first row)
            Row header = sheet.getRow(sheet.getFirstRowNum());
            if (header == null) {
                return olpns; // empty
            }

            int testcaseCol = -1;
            int olpnsCol = -1;

            for (int c = header.getFirstCellNum(); c < header.getLastCellNum(); c++) {
                String headerName = formatter.formatCellValue(header.getCell(c)).trim();
                if ("Testcase".equalsIgnoreCase(headerName)) {
                    testcaseCol = c;
                } else if ("OLPNs".equalsIgnoreCase(headerName)) {
                    olpnsCol = c;
                }
            }

            if (testcaseCol == -1 || olpnsCol == -1) {
                throw new IllegalStateException("Required columns 'Testcase' or 'OLPNs' not found in header.");
            }

            // Iterate data rows
            for (int r = sheet.getFirstRowNum() + 1; r <= sheet.getLastRowNum(); r++) {
                Row row = sheet.getRow(r);
                if (row == null) continue;

                String tc = formatter.formatCellValue(row.getCell(testcaseCol)).trim();
                if (tc.equals(testcaseValue)) {
                    String olpn = formatter.formatCellValue(row.getCell(olpnsCol)).trim();
                    if (!olpn.isEmpty()) {
                        olpns.add(olpn);
                    }
                }
            }
        }
        return olpns;
    }
    public static void endcart() throws InterruptedException {
        By endCartButton = By.cssSelector("button[data-component-id='action_endcart_button']");
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));

        // Wait until the button is clickable and then click
        WebElement button = wait.until(ExpectedConditions.elementToBeClickable(endCartButton));
        Thread.sleep(3000);
        captureScreenshot("End Cart ");
        DocPathManager.saveSharedDocument();
        System.out.println("End Cart screenshot done");
        Thread.sleep(3000);
        button.click();
    }
    public static void enterAutoGeneratedTote() throws InterruptedException {
        // Generate tote value: "TOT" + 8 random digits
        String toteValue = "TT1" + String.format("%05d", ThreadLocalRandom.current().nextInt(100000));
        System.out.println("Generated Tote: " + toteValue);

        // Locator for the tote input field
        By toteLocator = By.cssSelector("input[data-component-id='accepttote_barcodetextfield_tote']");

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));

        // Wait until the field is clickable
        WebElement toteField = wait.until(ExpectedConditions.elementToBeClickable(toteLocator));

        // Click and clear safely
//        toteField.click();
//        toteField.sendKeys(Keys.chord(Keys.CONTROL, "a")); // select all
//        toteField.sendKeys(Keys.DELETE);                   // clear



        // Enter the tote value
        toteField.sendKeys(toteValue);
        Thread.sleep(3000);
        captureScreenshot("Tote");
        DocPathManager.saveSharedDocument();
        System.out.println("Tote screenshot done");
        Thread.sleep(3000);

        // Press Enter to submit
        toteField.sendKeys(Keys.ENTER);

        // Optional: log the generated tote
        System.out.println("Generated Tote: " + toteValue);
    }
    public static List<String> getTaskGroupsForTestcase1(String filePath, String sheetName, String testcaseId) throws IOException {
        Set<String> taskGroups = new LinkedHashSet<>();
        try (FileInputStream fis = new FileInputStream(filePath);
             Workbook workbook = new XSSFWorkbook(fis)) {

            Sheet sheet = workbook.getSheet(sheetName);

            for (Row row : sheet) {
                if (row.getRowNum() == 0) continue; // Skip header

                Cell testcaseCell = row.getCell(0);
                Cell taskGroupCell = row.getCell(3);

                if (testcaseCell == null || taskGroupCell == null) {
                    continue; // Skip rows with missing cells
                }

                String testcase = testcaseCell.getStringCellValue().trim();
                if (testcase.equalsIgnoreCase(testcaseId)) {
                    String taskgroup = taskGroupCell.getStringCellValue().trim();
                    if (!taskgroup.isEmpty()) {
                        taskGroups.add(taskgroup);
                    }
                }
            }
        }
        return new ArrayList<>(taskGroups);
    }



    public static void captureScreenshot(String fileName) {
        try {
            File srcFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
            try (FileInputStream fis = new FileInputStream(srcFile)) {
                XWPFDocument document = DocPathManager.getSharedDocument();
                XWPFParagraph paragraph = document.createParagraph();
                XWPFRun run = paragraph.createRun();
                run.setText("Screenshot: " + fileName);
                run.addBreak();
                run.addPicture(fis,
                        Document.PICTURE_TYPE_PNG,
                        fileName + ".png",
                        Units.toEMU(500),
                        Units.toEMU(300));
            }
            System.out.println("Screenshot added to document: " + fileName);
        } catch (Exception e) {
            System.out.println("Error capturing screenshot: " + e.getMessage());
        }
    }
    public static void captureAllCardsScreenshots() throws InterruptedException, IOException {
        XWPFDocument document = DocPathManager.getSharedDocument(); // shared doc
        List<WebElement> rows = driver.findElements(By.cssSelector("[role='main'] card-view"));
        int i = 1;
        for (WebElement row : rows) {
            ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView({block:'center'});", row);
            Thread.sleep(500);
            captureScreenshotRow(row, i, document);
            Thread.sleep(800);
            i++;
        }
    }

    public static void captureScreenshotRow(WebElement ele, int i, XWPFDocument document) {
        try {
            File srcFile = ele.getScreenshotAs(OutputType.FILE);
            try (FileInputStream fis = new FileInputStream(srcFile)) {
                XWPFParagraph paragraph = document.createParagraph();
                XWPFRun run = paragraph.createRun();
                run.setText("Card Row Screenshot: " + i);
                run.addBreak();
                run.addPicture(fis, Document.PICTURE_TYPE_PNG, i + ".png", Units.toEMU(500), Units.toEMU(100));
            }
            System.out.println("Row screenshot added: " + i);
        } catch (Exception e) {
            System.out.println("Error capturing row screenshot: " + e.getMessage());
        }
    }




}